In [ ]:
import numpy as np
import pandas as pd

In [22]:
df=pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [23]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [24]:
df['Insulin']=df['Insulin'].replace(0,df['Insulin'].mean())
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0            6      148             72             35   79.799479  33.6   
1            1       85             66             29   79.799479  26.6   
2            8      183             64              0   79.799479  23.3   
3            1       89             66             23   94.000000  28.1   
4            0      137             40             35  168.000000  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [25]:
df['SkinThickness']=df['SkinThickness'].replace(0,df['SkinThickness'].mean())
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0            6      148             72      35.000000   79.799479  33.6   
1            1       85             66      29.000000   79.799479  26.6   
2            8      183             64      20.536458   79.799479  23.3   
3            1       89             66      23.000000   94.000000  28.1   
4            0      137             40      35.000000  168.000000  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

<h3>Feature Scaling<h3>

In [26]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
df_std=std.fit_transform(df)
df_std

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.46849198,
         1.4259954 ,  1.36589591],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.36506078,
        -0.19067191, -0.73212021],
       [ 1.23388019,  1.94372388, -0.26394125, ...,  0.60439732,
        -0.10558415,  1.36589591],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.68519336,
        -0.27575966, -0.73212021],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.37110101,
         1.17073215,  1.36589591],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.47378505,
        -0.87137393, -0.73212021]])

<h3>Train_Test<h3>

In [27]:
x=df.drop(['Outcome'],axis=1)
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0            6      148             72      35.000000   79.799479  33.6   
1            1       85             66      29.000000   79.799479  26.6   
2            8      183             64      20.536458   79.799479  23.3   
3            1       89             66      23.000000   94.000000  28.1   
4            0      137             40      35.000000  168.000000  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [28]:
y=df.iloc[:,8:9]
y.head()


Outcome
0        1
1        0
2        1
3        0
4        1

In [29]:
import sklearn
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=3)

In [30]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(solver='lbfgs',max_iter=100)
lr.fit(X_train,Y_train.values.ravel())
lr.score(X_test,Y_test)

C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7445887445887446

In [31]:
#SUPPORT VECTOR
from sklearn import svm
from sklearn.svm import SVC
clf=SVC()
clf.fit(X_train,Y_train.values.ravel())
clf.score(X_test,Y_test)

0.7012987012987013

In [32]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=30)
rf.fit(X_train,Y_train.values.ravel())
rf.score(X_test,Y_test)

0.7402597402597403

In [33]:
#NEAREST NEIGHBOR
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train.values.ravel())
knn.score(X_test,Y_test)

0.6926406926406926

In [34]:
#DECISION TREE
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=2)
dt.fit(X_train,Y_train.values.ravel())
dt.score(X_test,Y_test)

0.6796536796536796

<h3>K Fold Cross Validation<h3>

In [35]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [36]:
from sklearn.model_selection import cross_val_score
score_lr=cross_val_score(lr,X_train,Y_train.values.ravel())   #LOGISTIC REGRESSION
print(score_lr)                                              
score_svm=cross_val_score(clf,X_train,Y_train.values.ravel())  #SUPPORT VECTOR
print(score_svm)
score_rf=cross_val_score(rf,X_train,Y_train.values.ravel())    #RANDOM FOREST
print(score_rf)
score_knn=cross_val_score(knn,X_train,Y_train.values.ravel())   #NEAREST NEIGHBOR
print(score_knn)
score_dt=cross_val_score(dt,X_train,Y_train.values.ravel())     #DECISION TREE
print(score_dt)

C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/

[0.81481481 0.7962963  0.70093458 0.8411215  0.75700935]
[0.81481481 0.80555556 0.71028037 0.79439252 0.77570093]
[0.76851852 0.78703704 0.71028037 0.79439252 0.78504673]
[0.73148148 0.76851852 0.61682243 0.71028037 0.71028037]
[0.78703704 0.7962963  0.69158879 0.79439252 0.74766355]


In [37]:
print(f"mean lr score :{score_lr.mean()}")       #LOGISTIC REGRESSION
print(f"mean svm score :{score_svm.mean()}")     #SUPPORT VECTOR 
print(f"mean rf score :{score_rf.mean()}")       #RANDOM FOREST
print(f"mean knn score :{score_knn.mean()}")     #NEAREST NEIGHBOR
print(f"mean dt score :{score_dt.mean()}")       #DECISION TREE

mean lr score :0.7820353063343717
mean svm score :0.7801488404292142
mean rf score :0.7690550363447559
mean knn score :0.7074766355140187
mean dt score :0.7633956386292835


<h3>Parameter Tuning Using Grid Search CV<h3>

In [38]:
from sklearn.model_selection import GridSearchCV


In [39]:
#LOGISTIC REGRESSION
parameters={'penalty':['l1','l2']}
grid=GridSearchCV(lr,parameters,cv=5).fit(X_train,Y_train.values.ravel())
print(grid.best_params_)
grid.best_score_

C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/

{'penalty': 'l2'}


C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [       nan 0.78203531]
  warnings.warn(
C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7820353063343717

In [40]:
#SUPPORT VECTOR MACHINE
parameters={'kernel':('linear','rbf'),'C':[1,10]}
best_estimator=SVC(gamma='scale')
grid=GridSearchCV(best_estimator,parameters,cv=5).fit(X_train,Y_train.values.ravel())
print(grid.best_params_)
grid.best_score_

{'C': 1, 'kernel': 'linear'}


0.7894427137417791

In [30]:
#RANDOM FOREST
parameters={'n_estimators':[1,5,10,20],
           'max_features':['auto','sqrt','log2'],
           'max_depth':[4,5,6,7,8],
           'criterion':['gini','entropy']}
grid=GridSearchCV(rf,parameters,cv=5).fit(X_train,Y_train.values.ravel())
print(grid.best_params_)
grid.best_score_


{'criterion': 'gini', 'max_depth': 5, 'max_features': 'auto', 'n_estimators': 20}


0.7894946348217377

In [41]:
#NEAREST NEIGHBOR
k_range=list(range(1,60))
weight_options=['uniform','distance']
parameters={'n_neighbors':k_range,
           'weights':weight_options}
grid=GridSearchCV(knn,parameters,cv=5).fit(X_train,Y_train.values.ravel())
print(grid.best_params_)
grid.best_score_


{'n_neighbors': 30, 'weights': 'distance'}


0.7708376600899965

In [42]:
#DECISION TREE
parameters={'max_features':['auto','sqrt','log2'],
           'max_depth':[5,6,7,8,9],
           'criterion':['gini','entropy']}
grid=GridSearchCV(dt,parameters,cv=5).fit(X_train,Y_train.values.ravel())
print(grid.best_params_)
grid.best_score_


{'criterion': 'entropy', 'max_depth': 5, 'max_features': 'log2'}


0.7653167185877466

#From the above testing of algorithms we can conclude "RANDON FOREST" is the best fit algorithm for diabities dataset